kind: Service
apiVersion: v1
metadata:
  name: "{{.Chart.Name}}-{{.Chart.Version}}"
  labels: {{- include "spring.labels" . | indent 4}}
spec:
  selector: {{- include "spring.labels" . | indent 4}}
  type: {{.Values.service.type}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
