apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  GIT_URL: https://github.com/zinneranast/k8s-devops.git

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cdn
      initContainers:
      - name: git
        image: alpine/git:latest
        command: ["git"]
        args: ["clone", "$(GIT_URL)", "/cdn"]
        env:
        - name: GIT_URL
          valueFrom:
            configMapKeyRef:
              name: nginx
              key: GIT_URL
        volumeMounts:
        - mountPath: /cdn
          name: cdn
      volumes:
      - name: cdn
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: nginx
  type: LoadBalancer
